### ISSUE TITLE
Memory Leak Detect Tools

### ISSUE THREAD

**Issue by seenyea** [kirillzyusko/react-native-bundle-splitter#17] opened 2021-03-01 13:42 UTC
**Is your feature request related to a problem? Please describe.**
when I rewrite my page following the step by the document, but two main problem cause:
1. navigation.goBack() dose not cool
2. the static props does not cool

but let it my pc alone a while, what a amazing! Everything goes cool

**Describe the solution you'd like**
Supply a Memory Leak Detect Tool

**Comment by kirillzyusko** [comment] 2021-03-01 15:39
Hi @seenyea 

Could you please provide more details?

1. In which cases `navigation.goBack()` doesn't work? Could you create small reproducible demo?
2. What you mean by static props? static navigation options? You can not continue use them. Please, read docs how this support is implemented in this library: https://kirillzyusko.github.io/react-native-bundle-splitter/docs/static-options

What you mean by memory leaks? Have you found them in application?

**Comment by seenyea** [comment] 2021-03-02 11:55
Problem 1 and problem 2 occur randomly(about 1times per 10 times) in react native navigation v3.
React native navigation v3 support static props [https://reactnavigation.org/docs/3.x/headers](https://reactnavigation.org/docs/3.x/headers)
here are some code snap

**Comment by kirillzyusko** [comment] 2021-03-02 12:08
@seenyea I know, that it supports. And I'm using this fact in my library.

The reason why I moved static fields outside of component was quite simple. In this options you can specify some important things, such as style for header, title and so on, right? If you will do a lazy loading of these props - during transition between screens you will see default header and after some time (when component will be loaded) you will see proper elements.
And it will be not good from UI perspective.

I could try to inject static props from component when you are doing `preload`, but... At the point of designing a library I knew, that in react-navigation v5 you will not need to use static props. Instead of it you can declare all options straight in markup. And I didn't want to add additional complexity into library and decided to stick with simple approach :)

**Comment by seenyea** [comment] 2021-03-04 13:20
> The reason why I moved static fields outside of component was quite simple. In this options you can specify some important things, such as style for header, title and so on, right?

I think the final ```OptimizedComponent```  need set static properties at first, or it may cause ```state no routes``` error, especially for tabs.

**Comment by kirillzyusko** [comment] 2021-03-04 15:59
@seenyea it sets static props: https://github.com/kirillzyusko/react-native-bundle-splitter/blob/master/src/optimized.tsx#L54

If you pass `static` into `register` function - everything should be okay.

**Comment by kirillzyusko** [comment] 2021-03-15 19:54
Closing this issue as no proof provided about memory leaks.

**Closed by kirillzyusko** 2021-03-15 19:54 UTC
Labels: Feature
